/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora.pkg2;

import javax.swing.JOptionPane;

/**
 *
 * @author Cristian
 */
public class IntCalculo extends javax.swing.JFrame {

    /**
     * Creates new form IntCalculo
     */
    public IntCalculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLprimerNum = new javax.swing.JLabel();
        jLsegundoNum = new javax.swing.JLabel();
        jTprimerNum = new javax.swing.JTextField();
        jTsegundoNum = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jBsumar = new javax.swing.JButton();
        jBlimpiar = new javax.swing.JButton();
        jBresta = new javax.swing.JButton();
        jbMultiplicar = new javax.swing.JButton();
        jbDividir = new javax.swing.JButton();
        jLresultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 0, 0));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("CALCULAR");

        jLprimerNum.setText("PRIMER NUMERO :");

        jLsegundoNum.setText("SEGUNDO NUMERO:");

        jTprimerNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTprimerNumActionPerformed(evt);
            }
        });

        jTsegundoNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTsegundoNumActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setForeground(new java.awt.Color(0, 0, 204));

        jBsumar.setText("Sumar");
        jBsumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsumarActionPerformed(evt);
            }
        });

        jBlimpiar.setText("Limpiar");
        jBlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBlimpiarActionPerformed(evt);
            }
        });

        jBresta.setText("Resta");
        jBresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBrestaActionPerformed(evt);
            }
        });

        jbMultiplicar.setText("Multiplicar");
        jbMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMultiplicarActionPerformed(evt);
            }
        });

        jbDividir.setText("Dividir");
        jbDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDividirActionPerformed(evt);
            }
        });

        jLresultado.setBackground(new java.awt.Color(255, 255, 51));
        jLresultado.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLresultado.setForeground(new java.awt.Color(0, 0, 204));
        jLresultado.setText("resultado: ");
        jLresultado.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLresultadoAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBsumar)
                .addGap(18, 18, 18)
                .addComponent(jBresta)
                .addGap(31, 31, 31)
                .addComponent(jbMultiplicar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jbDividir)
                .addGap(29, 29, 29))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jBlimpiar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLresultado, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBsumar)
                    .addComponent(jBresta)
                    .addComponent(jbMultiplicar)
                    .addComponent(jbDividir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jBlimpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLresultado)
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLprimerNum, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLsegundoNum))
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTprimerNum, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTsegundoNum, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(256, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLprimerNum)
                    .addComponent(jTprimerNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLsegundoNum))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jTsegundoNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTprimerNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTprimerNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTprimerNumActionPerformed

    private void jTsegundoNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTsegundoNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTsegundoNumActionPerformed

    private void jBsumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsumarActionPerformed
    
        try  {
       int num1 = Integer.parseInt(jTprimerNum.getText());
       int num2 = Integer.parseInt(jTsegundoNum.getText());
       
       int  resul =num1 + num2 ;
       
       jLresultado.setText("EL RESULTADO ES: " + resul);
        } catch (NumberFormatException nf){
            JOptionPane.showMessageDialog(this, "Ingresar solo numeros");
        }
            
    }//GEN-LAST:event_jBsumarActionPerformed

    private void jLresultadoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLresultadoAncestorAdded
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_jLresultadoAncestorAdded

    private void jBlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBlimpiarActionPerformed
       jTprimerNum.setText("");
       jTsegundoNum.setText("");
       jLresultado.setText("resultado");
       
       
       
    }//GEN-LAST:event_jBlimpiarActionPerformed

    private void jBrestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBrestaActionPerformed
        // TODO add your handling code here:
           try  {
       int num1 = Integer.parseInt(jTprimerNum.getText());
       int num2 = Integer.parseInt(jTsegundoNum.getText());
       
       int  resul =num1 - num2 ;
       
       jLresultado.setText("EL RESULTADO ES: " + resul);
        } catch (NumberFormatException nf){
            JOptionPane.showMessageDialog(this, "Ingresar solo numeros");
        }
    }//GEN-LAST:event_jBrestaActionPerformed

    private void jbMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMultiplicarActionPerformed
        try  {
       int num1 = Integer.parseInt(jTprimerNum.getText());
       int num2 = Integer.parseInt(jTsegundoNum.getText());
       
       int  resul =num1 * num2 ;
       
       jLresultado.setText("EL RESULTADO ES: " + resul);
        } catch (NumberFormatException nf){
            JOptionPane.showMessageDialog(this, "Ingresar solo numeros");
        }
    }//GEN-LAST:event_jbMultiplicarActionPerformed

    private void jbDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDividirActionPerformed
       try  {
       int num1 = Integer.parseInt(jTprimerNum.getText());
       int num2 = Integer.parseInt(jTsegundoNum.getText());
       
       int  resul =num1 / num2 ;
       
       jLresultado.setText("EL RESULTADO ES: " + resul);
        } catch (NumberFormatException nf){
            JOptionPane.showMessageDialog(this, "Ingresar solo numeros");
        }
    }//GEN-LAST:event_jbDividirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntCalculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntCalculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntCalculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntCalculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntCalculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBlimpiar;
    private javax.swing.JButton jBresta;
    private javax.swing.JButton jBsumar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLprimerNum;
    private javax.swing.JLabel jLresultado;
    private javax.swing.JLabel jLsegundoNum;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTprimerNum;
    private javax.swing.JTextField jTsegundoNum;
    private javax.swing.JButton jbDividir;
    private javax.swing.JButton jbMultiplicar;
    // End of variables declaration//GEN-END:variables
}
